language: rust
sudo: required

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

rust:
  - stable
  - beta
  - nightly

script:
  - |
      travis-cargo build &&
      travis-cargo test

after_success:
  - travis-cargo coveralls
