environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      MSYS_BITS: 64
    - TARGET: i686-pc-windows-gnu
      MSYS_BITS: 32
    - TARGET: x86_64-pc-windows-msvc
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
    - TARGET: i686-pc-windows-msvc
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - set PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MSYS_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS_BITS%\bin
  - if defined VCVARS call "%VCVARS%"
  - rustc -V
  - cargo -V

build_script:
  - cargo build --verbose

test_script:
  - cargo test -- --nocapture
