[package]
name = "ruplicity"
version = "0.1.0"
authors = ["mbrt"]

[features]
default = []
lint = ["clippy"]

[dependencies]
flate2 = "0.2"
tar = "0.3.1"
regex = "0.1.8"
try_opt = "0.1.1"
time = "0.1.32"

# optional, working only on nightly
clippy = { version = "*", optional = true }
