[package]
name = "ruplicity"
version = "0.1.0"
authors = ["mbrt"]
description = "Browse duplicity backups"
repository = "https://github.com/mbrt/ruplicity"
readme = "README.md"
license = "MIT"
keywords = ["duplicity", "backup"]

[features]
default = []
unstable = ["clippy"]

[dependencies]
flate2 = "0.2"
tar = "0.3"
regex = "0.1"
try_opt = "0.1"
time = "0.1"
byteorder = "0.4"
tabwriter = "0.1"

# bin dependencies
clap = "1.5"

# optional, working only on nightly
clippy = { version = "*", optional = true }
